export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL';

export const POPULAR_MOVIE_LIST_REQUEST = 'POPULAR_MOVIE_LIST_REQUEST';
export const POPULAR_MOVIE_LIST_SUCCESS = 'POPULAR_MOVIE_LIST_SUCCESS';
export const POPULAR_MOVIE_LIST_FAIL = 'POPULAR_MOVIE_LIST_FAIL';

export const LATEST_MOVIE_REQUEST = 'LATEST_MOVIE_REQUEST';
export const LATEST_MOVIE_SUCCESS = 'LATEST_MOVIE_SUCCESS';
export const LATEST_MOVIE_FAIL = 'LATEST_MOVIE_FAIL';

export const FAVOURITE_MOVIE_LIST_REQUEST = 'FAVOURITE_MOVIE_LIST_REQUEST';
export const FAVOURITE_MOVIE_LIST_SUCCESS = 'FAVOURITE_MOVIE_LIST_SUCCESS';
export const FAVOURITE_MOVIE_LIST_FAIL = 'FAVOURITE_MOVIE_LIST_FAIL';

export const ADD_FAVOURITE_REQUEST = 'ADD_FAVOURITE_REQUEST';
export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS';
export const ADD_FAVOURITE_FAIL = 'ADD_FAVOURITE_FAIL';

export const REMOVE_FAVOURITE_REQUEST = 'REMOVE_FAVOURITE_REQUEST';
export const REMOVE_FAVOURITE_SUCCESS = 'REMOVE_FAVOURITE_SUCCESS';
export const REMOVE_FAVOURITE_FAIL = 'REMOVE_FAVOURITE_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_INFO_RESET = 'USER_REGISTER_INFO_RESET';